apiVersion: v1
kind: Service
metadata:
  name: svc-sys-noticias
spec:
  type: NodePort
  selector:
    app: sys-noticias
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30001
    protocol: TCP
